apiVersion: apps/v1
kind: Deployment
metadata:
  name: hip-local-api
  labels:
    app: hip-local-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hip-local-api
  template:
    metadata:
      labels:
        app: hip-local-api
    spec:
      containers:
      - name: hip-local-api
        image: gcr.io/roi-hiplocal/api:v0.8
        env:
        - name: PORT
          value: "8085"
        ports:
        - containerPort: 8085
          name: "backend-server"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 60
---

apiVersion: v1
kind: Service
metadata: 
  name: hip-local-api-svc
spec: 
  ports: 
     -  port: 8085
        protocol: TCP
        targetPort: 8085
  selector: 
    app: hip-local-api
  type: NodePort
---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hip-local-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: hip-local-api
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60